remote_theme: ddc-java/ddc-day-book
repository_link:
  enabled: false
page_navigator:
  enabled: true
titles_from_headings:
  enabled: false
# Putting navigation links at the top or bottom of the sites
prev_next_navigation:
- bottom

# TODO Modify the contents below for the specific project. NOTE THE INDENTATION!

title: "Noted - Note Application"
description: "Trust me, it'll be cool!"
author:
  name: "Dorian Obisike"
  email: "dorianobisike@gmail.com"

# Do not change the following line.
  copyright: true
